export type FeeUnit = "per group / half day" | "per group / full day" | "per person / tour";

export type TourGuide = {
  id: string;
  name: string;
  title: string;
  image: string;
  bio: string;
  rating: number;
  tours: number;
  years: number;
  languages: string[];
  specialties: string[];
  /** Specific places this guide covers. Empty when cityWide. */
  placeIds: string[];
  /** Shows on every place in the destination — a full city tour. */
  cityWide: boolean;
  fee: number;
  feeUnit: FeeUnit;
  groupSize: string;
  includes: string[];
  itinerary: string[];
  cancellation: string;
};

export const GUIDES: Record<string, TourGuide[]> = {
  santorini: [
    {
      id: "g-sant-1",
      name: "Nikos Alexiou",
      title: "Licensed archaeology guide",
      image: "/images/guide-sant-1.jpg",
      bio: "Trained archaeologist who worked on the Akrotiri site for six seasons before guiding full time. Explains the Minoan world without a single dull minute.",
      rating: 4.9,
      tours: 340,
      years: 14,
      languages: ["English", "Greek", "German"],
      specialties: ["Archaeology", "History", "Museums"],
      placeIds: ["p-sant-1", "p-sant-4", "p-sant-5"],
      cityWide: false,
      fee: 180,
      feeUnit: "per group / half day",
      groupSize: "Up to 8 people",
      includes: ["Hotel pickup", "Site commentary", "Bottled water"],
      itinerary: [
        "Pickup from your hotel or Fira bus station",
        "Akrotiri excavations with roofed site walkthrough",
        "Museum of Prehistoric Thera to see the lifted frescoes",
        "Optional extension up to Ancient Thera",
      ],
      cancellation: "Free up to 24h before",
    },
    {
      id: "g-sant-2",
      name: "Eleni Vardaki",
      title: "Sunset & photography guide",
      image: "/images/guide-sant-2.jpg",
      bio: "Island-born photographer who knows exactly where to stand when the light turns. Brings a spare camera and teaches as you go.",
      rating: 4.8,
      tours: 512,
      years: 9,
      languages: ["English", "Greek", "French"],
      specialties: ["Photography", "Viewpoints", "Sunset"],
      placeIds: ["p-sant-2", "p-sant-6", "p-sant-3"],
      cityWide: false,
      fee: 95,
      feeUnit: "per person / tour",
      groupSize: "Up to 6 people",
      includes: ["Photo coaching", "Edited photo set", "Sunset spot reservation"],
      itinerary: [
        "Golden-hour walk through Oia's back lanes",
        "Castle ruins for the caldera sunset",
        "Descent to Amoudi Bay for blue-hour shots",
      ],
      cancellation: "Free up to 48h before",
    },
    {
      id: "g-sant-3",
      name: "Yiannis Roussos",
      title: "Full island & food guide",
      image: "/images/guide-sant-3.jpg",
      bio: "Third-generation Santorinian. Runs the whole-island day: villages, wineries, beaches and the tavernas locals actually eat at.",
      rating: 4.9,
      tours: 288,
      years: 17,
      languages: ["English", "Greek", "Italian"],
      specialties: ["Food", "Wine", "Full city tour"],
      placeIds: [],
      cityWide: true,
      fee: 320,
      feeUnit: "per group / full day",
      groupSize: "Up to 7 people",
      includes: ["Air-conditioned van", "Wine tasting", "Taverna lunch", "All entrance fees"],
      itinerary: [
        "Morning: Akrotiri and Red Beach",
        "Midday: Assyrtiko winery tasting and taverna lunch",
        "Afternoon: Pyrgo village and Ancient Thera viewpoint",
        "Evening: Oia for the sunset",
      ],
      cancellation: "Free up to 24h before",
    },
  ],

  tokyo: [
    {
      id: "g-tok-1",
      name: "Aiko Tanaka",
      title: "Temples & culture guide",
      image: "/images/guide-tok-1.jpg",
      bio: "Former museum curator. Reads Tokyo like a document — shrine etiquette, Edo history and why the city looks the way it does.",
      rating: 4.9,
      tours: 430,
      years: 12,
      languages: ["English", "Japanese", "Mandarin"],
      specialties: ["Temples", "History", "Museums"],
      placeIds: ["p-tok-1", "p-tok-4", "p-tok-6"],
      cityWide: false,
      fee: 210,
      feeUnit: "per group / half day",
      groupSize: "Up to 8 people",
      includes: ["IC transit cards", "Shrine etiquette briefing", "Entrance fees"],
      itinerary: [
        "Senso-ji at opening hour, before the crowds",
        "Nakamise street with a stop for freshly grilled senbei",
        "Train to Meiji Jingu forest shrine",
        "Optional Tokyo National Museum finish in Ueno",
      ],
      cancellation: "Free up to 24h before",
    },
    {
      id: "g-tok-2",
      name: "Kenji Morita",
      title: "Night city & neon guide",
      image: "/images/guide-tok-2.jpg",
      bio: "Grew up between Shibuya and Shimokitazawa. Takes you from the scramble to the six-seat izakayas tourists never find.",
      rating: 4.8,
      tours: 620,
      years: 7,
      languages: ["English", "Japanese"],
      specialties: ["Nightlife", "Photography", "Cityscape"],
      placeIds: ["p-tok-2", "p-tok-5"],
      cityWide: false,
      fee: 110,
      feeUnit: "per person / tour",
      groupSize: "Up to 6 people",
      includes: ["Shibuya Sky ticket", "First round of drinks", "Late-night ramen"],
      itinerary: [
        "Shibuya Scramble from street level, then from Shibuya Sky",
        "Backstreet izakaya crawl through Nonbei Yokocho",
        "TeamLab Planets late session on request",
      ],
      cancellation: "Free up to 48h before",
    },
    {
      id: "g-tok-3",
      name: "Hiroshi Nakamura",
      title: "Full Tokyo day guide",
      image: "/images/guide-tok-3.jpg",
      bio: "Thirty years walking this city. Covers the whole map in a day and still gets you to the good breakfast sushi first.",
      rating: 5.0,
      tours: 890,
      years: 30,
      languages: ["English", "Japanese", "Korean"],
      specialties: ["Food", "Markets", "Full city tour"],
      placeIds: [],
      cityWide: true,
      fee: 420,
      feeUnit: "per group / full day",
      groupSize: "Up to 6 people",
      includes: ["Private van", "Breakfast at Tsukiji", "All transit", "Entrance fees"],
      itinerary: [
        "05:30 Tsukiji outer market breakfast",
        "Asakusa and Senso-ji",
        "Lunch in Ueno, then the National Museum",
        "Shibuya and Harajuku by evening",
      ],
      cancellation: "Free up to 24h before",
    },
  ],

  marrakech: [
    {
      id: "g-mar-1",
      name: "Youssef El Mansouri",
      title: "Medina & monuments guide",
      image: "/images/guide-mar-1.jpg",
      bio: "Licensed by the Moroccan tourism board and born inside the medina walls. Navigates the souks so you never feel lost or hustled.",
      rating: 4.9,
      tours: 760,
      years: 19,
      languages: ["English", "Arabic", "French", "Spanish"],
      specialties: ["Medina", "Architecture", "History"],
      placeIds: ["p-mar-1", "p-mar-2", "p-mar-3", "p-mar-5"],
      cityWide: false,
      fee: 140,
      feeUnit: "per group / half day",
      groupSize: "Up to 10 people",
      includes: ["All monument entries", "Mint tea stop", "Riad drop-off"],
      itinerary: [
        "Koutoubia gardens and the minaret story",
        "Bahia Palace courtyards and cedar ceilings",
        "Saadian Tombs",
        "Finish on Jemaa el-Fnaa as the food stalls open",
      ],
      cancellation: "Free up to 24h before",
    },
    {
      id: "g-mar-2",
      name: "Salma Bennani",
      title: "Gardens & design guide",
      image: "/images/guide-mar-2.jpg",
      bio: "Art historian focused on Moroccan craft. Explains zellige, Berber textiles and the Majorelle story with real depth.",
      rating: 4.8,
      tours: 295,
      years: 8,
      languages: ["English", "French", "Arabic"],
      specialties: ["Gardens", "Design", "Craft"],
      placeIds: ["p-mar-4", "p-mar-2"],
      cityWide: false,
      fee: 85,
      feeUnit: "per person / tour",
      groupSize: "Up to 8 people",
      includes: ["Majorelle & YSL tickets", "Berber museum entry", "Café stop"],
      itinerary: [
        "Jardin Majorelle at opening, before the queues",
        "Berber Museum inside the cobalt villa",
        "Yves Saint Laurent museum next door",
        "Walk through Guéliz design studios",
      ],
      cancellation: "Free up to 48h before",
    },
    {
      id: "g-mar-3",
      name: "Omar Chakir",
      title: "Full city & street food guide",
      image: "/images/guide-mar-3.jpg",
      bio: "Runs the whole-city day and eats his way through it. Knows which grill on the square is worth queuing for.",
      rating: 4.7,
      tours: 410,
      years: 6,
      languages: ["English", "Arabic", "French"],
      specialties: ["Food", "Souks", "Full city tour"],
      placeIds: [],
      cityWide: true,
      fee: 260,
      feeUnit: "per group / full day",
      groupSize: "Up to 8 people",
      includes: ["All tastings", "Monument entries", "Taxi transfers"],
      itinerary: [
        "Morning souk walk from Semmarine down to the dyers' quarter",
        "Lunch of tanjia and msemen",
        "Afternoon palaces and gardens",
        "Evening food stalls on Jemaa el-Fnaa",
      ],
      cancellation: "Free up to 24h before",
    },
  ],

  capetown: [
    {
      id: "g-cpt-1",
      name: "Sipho Ndlovu",
      title: "Mountain & hiking guide",
      image: "/images/guide-cpt-1.jpg",
      bio: "Mountain-qualified guide who has summited Table Mountain over a thousand times. Reads the weather so you never get caught out.",
      rating: 4.9,
      tours: 1020,
      years: 15,
      languages: ["English", "Xhosa", "Afrikaans"],
      specialties: ["Hiking", "Nature", "Photography"],
      placeIds: ["p-cpt-1", "p-cpt-5", "p-cpt-4"],
      cityWide: false,
      fee: 165,
      feeUnit: "per group / half day",
      groupSize: "Up to 8 people",
      includes: ["Trail permits", "Snacks and water", "Cableway down"],
      itinerary: [
        "Platteklip Gorge ascent at sunrise",
        "Summit walk to Maclear's Beacon",
        "Cableway descent, or continue to Kirstenbosch",
      ],
      cancellation: "Free up to 24h before · weather refund",
    },
    {
      id: "g-cpt-2",
      name: "Nadia Petersen",
      title: "Heritage & Bo-Kaap guide",
      image: "/images/guide-cpt-2.jpg",
      bio: "Cape Malay heritage specialist from Bo-Kaap itself. Tells the city's harder history honestly and cooks a mean koeksister.",
      rating: 5.0,
      tours: 380,
      years: 11,
      languages: ["English", "Afrikaans"],
      specialties: ["Heritage", "Food", "History"],
      placeIds: ["p-cpt-6", "p-cpt-2"],
      cityWide: false,
      fee: 90,
      feeUnit: "per person / tour",
      groupSize: "Up to 10 people",
      includes: ["Robben Island ferry ticket", "Bo-Kaap home cooking stop", "Museum entry"],
      itinerary: [
        "Bo-Kaap walking tour with a home kitchen visit",
        "Ferry to Robben Island from the Waterfront",
        "Prison tour led by a former political prisoner",
      ],
      cancellation: "Free up to 72h before · ferry dependent",
    },
    {
      id: "g-cpt-3",
      name: "Dawie Marais",
      title: "Peninsula & wildlife guide",
      image: "/images/guide-cpt-3.jpg",
      bio: "Naturalist who drives the full peninsula loop and knows where the penguins actually are on a cold morning.",
      rating: 4.8,
      tours: 640,
      years: 22,
      languages: ["English", "Afrikaans", "German"],
      specialties: ["Wildlife", "Nature", "Full city tour"],
      placeIds: [],
      cityWide: true,
      fee: 340,
      feeUnit: "per group / full day",
      groupSize: "Up to 6 people",
      includes: ["4x4 vehicle", "All reserve fees", "Binoculars", "Picnic lunch"],
      itinerary: [
        "Chapman's Peak drive",
        "Boulders Beach penguin colony",
        "Cape of Good Hope and the lighthouse walk",
        "Return via Kirstenbosch gardens",
      ],
      cancellation: "Free up to 24h before",
    },
  ],

  rio: [
    {
      id: "g-rio-1",
      name: "Lucas Ferreira",
      title: "Landmarks & viewpoints guide",
      image: "/images/guide-rio-1.jpg",
      bio: "Carioca who times the Corcovado train and the Sugarloaf cable car so you skip both queues and catch the light.",
      rating: 4.9,
      tours: 520,
      years: 10,
      languages: ["English", "Portuguese", "Spanish"],
      specialties: ["Viewpoints", "Landmarks", "Photography"],
      placeIds: ["p-rio-1", "p-rio-2"],
      cityWide: false,
      fee: 175,
      feeUnit: "per group / half day",
      groupSize: "Up to 8 people",
      includes: ["Cog train ticket", "Cable car ticket", "Hotel pickup"],
      itinerary: [
        "Early cog train up Corcovado to Christ the Redeemer",
        "Descent through Tijuca rainforest",
        "Two-stage Sugarloaf cable car timed for sunset",
      ],
      cancellation: "Free up to 24h before",
    },
    {
      id: "g-rio-2",
      name: "Beatriz Souza",
      title: "Art & neighbourhood guide",
      image: "/images/guide-rio-2.jpg",
      bio: "Grew up in Lapa. Walks you through Selarón's story, the samba houses and the street art that changes month to month.",
      rating: 4.8,
      tours: 340,
      years: 7,
      languages: ["English", "Portuguese"],
      specialties: ["Art", "Music", "Neighbourhoods"],
      placeIds: ["p-rio-4", "p-rio-6", "p-rio-5"],
      cityWide: false,
      fee: 70,
      feeUnit: "per person / tour",
      groupSize: "Up to 10 people",
      includes: ["Samba house entry", "Caipirinha stop", "Stadium tour ticket"],
      itinerary: [
        "Selarón Steps and the Lapa arches",
        "Street art walk through Santa Teresa",
        "Optional Maracanã pitch-side tour",
      ],
      cancellation: "Free up to 48h before",
    },
    {
      id: "g-rio-3",
      name: "Rafael Costa",
      title: "Full city & beach guide",
      image: "/images/guide-rio-3.jpg",
      bio: "Former lifeguard turned guide. Does the whole city in a day and teaches you posto etiquette on Ipanema.",
      rating: 4.7,
      tours: 455,
      years: 13,
      languages: ["English", "Portuguese", "French"],
      specialties: ["Beach", "Surf", "Full city tour"],
      placeIds: [],
      cityWide: true,
      fee: 300,
      feeUnit: "per group / full day",
      groupSize: "Up to 7 people",
      includes: ["Air-conditioned car", "Beach chairs", "All entrance fees", "Lunch"],
      itinerary: [
        "Morning at Christ the Redeemer",
        "Lunch in Ipanema",
        "Afternoon on the beach with chairs set up",
        "Arpoador rock for the sunset applause",
      ],
      cancellation: "Free up to 24h before",
    },
  ],

  bali: [
    {
      id: "g-bal-1",
      name: "Wayan Suarta",
      title: "Temple & ceremony guide",
      image: "/images/guide-bal-1.jpg",
      bio: "Balinese Hindu who guides at the island's water temples. Arranges sarongs and explains the purification ritual properly.",
      rating: 5.0,
      tours: 610,
      years: 18,
      languages: ["English", "Indonesian", "Balinese"],
      specialties: ["Temples", "Ceremony", "Culture"],
      placeIds: ["p-bal-2", "p-bal-4", "p-bal-5"],
      cityWide: false,
      fee: 120,
      feeUnit: "per group / half day",
      groupSize: "Up to 8 people",
      includes: ["Sarong and sash", "Temple donations", "Kecak dance seats"],
      itinerary: [
        "Tirta Empul holy spring with guided purification",
        "Sacred Monkey Forest walk",
        "Uluwatu clifftop temple for the sunset kecak fire dance",
      ],
      cancellation: "Free up to 24h before",
    },
    {
      id: "g-bal-2",
      name: "Kadek Ayu Pratiwi",
      title: "Rice terrace & nature guide",
      image: "/images/guide-bal-2.jpg",
      bio: "Farmer's daughter from Tegallalang. Explains the subak irrigation system and gets you there before the tour buses.",
      rating: 4.9,
      tours: 480,
      years: 9,
      languages: ["English", "Indonesian", "Dutch"],
      specialties: ["Nature", "Photography", "Villages"],
      placeIds: ["p-bal-1", "p-bal-6"],
      cityWide: false,
      fee: 60,
      feeUnit: "per person / tour",
      groupSize: "Up to 8 people",
      includes: ["Scooter or car transfer", "Terrace entry", "Coconut and fruit"],
      itinerary: [
        "Sunrise at Tegallalang before the crowds",
        "Walk down into the terraces with a farming family",
        "Coffee plantation tasting",
        "Finish at Canggu beach for sunset",
      ],
      cancellation: "Free up to 48h before",
    },
    {
      id: "g-bal-3",
      name: "Gede Arya",
      title: "Volcano trek & island guide",
      image: "/images/guide-bal-3.jpg",
      bio: "Certified Mount Batur trekking guide with a perfect safety record. Also runs the full-island day for people who want everything.",
      rating: 4.9,
      tours: 720,
      years: 11,
      languages: ["English", "Indonesian"],
      specialties: ["Adventure", "Hiking", "Full city tour"],
      placeIds: [],
      cityWide: true,
      fee: 280,
      feeUnit: "per group / full day",
      groupSize: "Up to 6 people",
      includes: ["Headlamps", "Summit breakfast", "Hot spring entry", "All transfers"],
      itinerary: [
        "03:30 pickup for the Mount Batur night ascent",
        "Sunrise breakfast cooked in volcanic steam",
        "Descent and natural hot springs",
        "Afternoon temples and rice terraces on the way back",
      ],
      cancellation: "Free up to 24h before · weather refund",
    },
  ],
};

/** Guides relevant to a specific place: place-specific first, then city-wide. */
export function guidesForPlace(destinationId: string, placeId: string): TourGuide[] {
  const all = GUIDES[destinationId] ?? [];
  return [
    ...all.filter((g) => !g.cityWide && g.placeIds.includes(placeId)),
    ...all.filter((g) => g.cityWide),
  ];
}

export function guidesForDestination(destinationId: string): TourGuide[] {
  return GUIDES[destinationId] ?? [];
}
