export type TravelerPost = {
  id: string;
  author: string;
  initials: string;
  image: string;
  caption: string;
  /** Matching place id from places-catalog, when the spot is bookable. */
  placeId?: string;
  placeName: string;
  city: string;
  country: string;
  likes: number;
  postedAgo: string;
  accent: "sunset" | "lagoon" | "grape" | "mango" | "leaf";
};

export const TRAVELER_POSTS: TravelerPost[] = [
  {
    id: "post-1",
    author: "Amara Bright",
    initials: "AB",
    image: "/images/post-penguins.jpg",
    caption: "Sat with the penguins for an hour. Nobody rushed me. Best $10 I've spent.",
    placeId: "p-cpt-3",
    placeName: "Boulders Beach Penguins",
    city: "Cape Town",
    country: "South Africa",
    likes: 1284,
    postedAgo: "2h ago",
    accent: "lagoon",
  },
  {
    id: "post-2",
    author: "Kenji Mori",
    initials: "KM",
    image: "/images/post-temple.jpg",
    caption: "Incense at 7am before the crowds — Senso-ji feels like a different city.",
    placeId: "p-tok-1",
    placeName: "Senso-ji Temple",
    city: "Tokyo",
    country: "Japan",
    likes: 942,
    postedAgo: "5h ago",
    accent: "sunset",
  },
  {
    id: "post-3",
    author: "Lina Haddad",
    initials: "LH",
    image: "/images/post-market.jpg",
    caption: "Got lost in the souk twice and found the best mint tea of my life.",
    placeId: "p-mar-6",
    placeName: "Souk Semmarine",
    city: "Marrakech",
    country: "Morocco",
    likes: 733,
    postedAgo: "8h ago",
    accent: "mango",
  },
  {
    id: "post-4",
    author: "Tomas Reyes",
    initials: "TR",
    image: "/images/post-zoo.jpg",
    caption: "Giraffes at golden hour. My camera roll is completely unusable now.",
    placeName: "City Safari Park",
    city: "Cape Town",
    country: "South Africa",
    likes: 611,
    postedAgo: "11h ago",
    accent: "leaf",
  },
  {
    id: "post-5",
    author: "Sofia Marin",
    initials: "SM",
    image: "/images/dest-santorini.jpg",
    caption: "Climbed to the castle two hours early. Worth every step for that sunset.",
    placeId: "p-sant-2",
    placeName: "Oia Sunset Castle",
    city: "Santorini",
    country: "Greece",
    likes: 2103,
    postedAgo: "1d ago",
    accent: "grape",
  },
  {
    id: "post-6",
    author: "Diego Alves",
    initials: "DA",
    image: "/images/dest-rio.jpg",
    caption: "Sunset applause at Arpoador is a real thing and I clapped the loudest.",
    placeId: "p-rio-3",
    placeName: "Ipanema Beach",
    city: "Rio de Janeiro",
    country: "Brazil",
    likes: 1476,
    postedAgo: "1d ago",
    accent: "sunset",
  },
  {
    id: "post-7",
    author: "Putu Ardana",
    initials: "PA",
    image: "/images/dest-bali.jpg",
    caption: "Rice terraces at 6am — cold, quiet, and completely empty.",
    placeId: "p-bal-1",
    placeName: "Tegallalang Rice Terraces",
    city: "Ubud",
    country: "Indonesia",
    likes: 869,
    postedAgo: "2d ago",
    accent: "leaf",
  },
  {
    id: "post-8",
    author: "Hana Okabe",
    initials: "HO",
    image: "/images/dest-tokyo.jpg",
    caption: "Barefoot through knee-deep water and infinite light. Bring shorts.",
    placeId: "p-tok-5",
    placeName: "TeamLab Planets",
    city: "Tokyo",
    country: "Japan",
    likes: 1552,
    postedAgo: "2d ago",
    accent: "grape",
  },
  {
    id: "post-9",
    author: "Yasmin Cherif",
    initials: "YC",
    image: "/images/dest-marrakech.jpg",
    caption: "That blue villa is even louder in person. Went twice in one day.",
    placeId: "p-mar-4",
    placeName: "Jardin Majorelle & YSL",
    city: "Marrakech",
    country: "Morocco",
    likes: 1024,
    postedAgo: "3d ago",
    accent: "lagoon",
  },
  {
    id: "post-10",
    author: "Nomsa Dlamini",
    initials: "ND",
    image: "/images/dest-capetown.jpg",
    caption: "Hiked Platteklip instead of the cable car. Legs gone, view earned.",
    placeId: "p-cpt-1",
    placeName: "Table Mountain",
    city: "Cape Town",
    country: "South Africa",
    likes: 1330,
    postedAgo: "4d ago",
    accent: "mango",
  },
  {
    id: "post-11",
    author: "Marco Bianchi",
    initials: "MB",
    image: "/images/dest-santorini.jpg",
    caption: "300 steps down to Amoudi, grilled octopus, then 300 steps back up.",
    placeId: "p-sant-6",
    placeName: "Amoudi Bay",
    city: "Santorini",
    country: "Greece",
    likes: 588,
    postedAgo: "5d ago",
    accent: "sunset",
  },
  {
    id: "post-12",
    author: "Clara Souza",
    initials: "CS",
    image: "/images/dest-rio.jpg",
    caption: "215 tiled steps and every single one is from a different country.",
    placeId: "p-rio-4",
    placeName: "Selarón Steps",
    city: "Rio de Janeiro",
    country: "Brazil",
    likes: 977,
    postedAgo: "6d ago",
    accent: "grape",
  },
];
