export type ProfessionId =
  | "photographer"
  | "videographer"
  | "chef"
  | "barber"
  | "shopper"
  | "interpreter"
  | "security"
  | "babysitter"
  | "event-planner"
  | "freelancer";

export type Profession = {
  id: ProfessionId;
  label: string;
  blurb: string;
};

export const PROFESSIONS: Profession[] = [
  { id: "photographer", label: "Photographer", blurb: "Portrait, street and golden-hour shoots" },
  { id: "videographer", label: "Videographer", blurb: "Cinematic reels and travel films" },
  { id: "chef", label: "Private chef / cook", blurb: "Home dining, local menus, meal prep" },
  { id: "barber", label: "Barber / stylist", blurb: "Cuts, shaves, braids and blowouts" },
  { id: "shopper", label: "Personal shopper", blurb: "Markets, boutiques, tailoring runs" },
  { id: "interpreter", label: "Interpreter / translator", blurb: "Live translation for meetings and trips" },
  { id: "security", label: "Private security", blurb: "Licensed close protection and drivers" },
  { id: "babysitter", label: "Babysitter / nanny", blurb: "Vetted childcare, day or evening" },
  { id: "event-planner", label: "Event planner", blurb: "Proposals, birthdays, small weddings" },
  { id: "freelancer", label: "Freelancer / other", blurb: "Fixers, drivers, assistants and more" },
];

export const PRO_CITIES = [
  "Santorini",
  "Tokyo",
  "Marrakech",
  "Cape Town",
  "Rio de Janeiro",
  "Bali",
];

export type TravelPro = {
  id: string;
  professionId: ProfessionId;
  city: string;
  name: string;
  headline: string;
  image: string;
  bio: string;
  rating: number;
  jobs: number;
  years: number;
  languages: string[];
  skills: string[];
  rate: number;
  rateUnit: string;
  includes: string[];
  packages: { name: string; detail: string; price: number }[];
  availability: string;
  cancellation: string;
};

export const PROS: TravelPro[] = [
  {
    id: "pro-photographer-1",
    professionId: "photographer",
    city: "Santorini",
    name: "Elena Marousi",
    headline: "Caldera & golden-hour portrait photographer",
    image: "/images/pro-photographer-1.jpg",
    bio: "Twelve years shooting couples and families along the caldera rim. Knows every quiet blue-dome corner before the tour buses arrive, and edits fast so you leave with photos, not promises.",
    rating: 4.9,
    jobs: 420,
    years: 12,
    languages: ["English", "Greek"],
    skills: ["Portraits", "Couples", "Golden hour", "Drone"],
    rate: 280,
    rateUnit: "per 2-hour shoot",
    includes: ["40+ edited photos", "Online gallery in 72h", "Location scouting", "Posing guidance"],
    packages: [
      { name: "Sunrise mini", detail: "60 minutes, 20 edits", price: 180 },
      { name: "Classic shoot", detail: "2 hours, 2 locations, 40 edits", price: 280 },
      { name: "Full day story", detail: "6 hours, whole-island coverage", price: 750 },
    ],
    availability: "Most mornings and evenings, 48h notice",
    cancellation: "Free up to 24h before",
  },
  {
    id: "pro-photographer-2",
    professionId: "photographer",
    city: "Tokyo",
    name: "Kenji Watanabe",
    headline: "Neon street & documentary photographer",
    image: "/images/pro-photographer-2.jpg",
    bio: "Former magazine photojournalist who now walks visitors through Shinjuku and Shibuya after dark. Documentary style — no stiff posing, just your trip as it actually happened.",
    rating: 4.8,
    jobs: 310,
    years: 15,
    languages: ["Japanese", "English"],
    skills: ["Street", "Night", "Documentary", "Film"],
    rate: 240,
    rateUnit: "per 2-hour walk",
    includes: ["35mm + digital", "30 edited photos", "Route planning", "Rain backup plan"],
    packages: [
      { name: "Neon night walk", detail: "2 hours, Shinjuku to Golden Gai", price: 240 },
      { name: "Two-district day", detail: "4 hours, day and night", price: 430 },
      { name: "Film only", detail: "Analogue roll, hand scanned", price: 300 },
    ],
    availability: "Evenings, and weekends all day",
    cancellation: "Free up to 48h before",
  },
  {
    id: "pro-videographer-1",
    professionId: "videographer",
    city: "Bali",
    name: "Putu Ardana",
    headline: "Cinematic travel film-maker",
    image: "/images/pro-videographer-1.jpg",
    bio: "Shoots on gimbal and drone, edits like a short film. Rice terraces at dawn, waterfalls, surf sessions — you get a colour-graded film plus vertical cuts for social.",
    rating: 4.9,
    jobs: 260,
    years: 9,
    languages: ["Indonesian", "English"],
    skills: ["Drone", "Gimbal", "Colour grading", "Reels"],
    rate: 390,
    rateUnit: "per half day",
    includes: ["3-4 min film", "3 vertical reels", "Licensed music", "Drone coverage"],
    packages: [
      { name: "Reel pack", detail: "3 hours, 3 vertical reels", price: 250 },
      { name: "Half-day film", detail: "5 hours, full edit", price: 390 },
      { name: "Trip documentary", detail: "3 days across the island", price: 1450 },
    ],
    availability: "Daily, book 3 days ahead",
    cancellation: "50% refund inside 48h",
  },
  {
    id: "pro-videographer-2",
    professionId: "videographer",
    city: "Rio de Janeiro",
    name: "Marina Castro",
    headline: "Event & lifestyle videographer",
    image: "/images/pro-videographer-2.jpg",
    bio: "Covers proposals, birthdays and beach days from Ipanema to Pedra Bonita. Discreet on the day, quick on the turnaround — highlights land within a week.",
    rating: 4.8,
    jobs: 190,
    years: 7,
    languages: ["Portuguese", "English", "Spanish"],
    skills: ["Events", "Proposals", "Lifestyle", "Two-camera"],
    rate: 340,
    rateUnit: "per half day",
    includes: ["Highlight film", "Raw footage drive", "Second camera", "Audio recording"],
    packages: [
      { name: "Proposal capture", detail: "90 minutes, hidden-camera style", price: 220 },
      { name: "Half-day event", detail: "5 hours, two cameras", price: 340 },
      { name: "Full celebration", detail: "10 hours plus next-day edit", price: 690 },
    ],
    availability: "Weekends fill fast — book early",
    cancellation: "Free up to 5 days before",
  },
  {
    id: "pro-chef-1",
    professionId: "chef",
    city: "Marrakech",
    name: "Hicham Benali",
    headline: "Private chef — Moroccan home cooking",
    image: "/images/pro-chef-1.jpg",
    bio: "Trained in a riad kitchen in the medina, cooks tagine, pastilla and slow lamb at your villa. Shops the souk that morning, and will teach you the spice blends if you ask.",
    rating: 5,
    jobs: 340,
    years: 16,
    languages: ["Arabic", "French", "English"],
    skills: ["Moroccan", "Vegetarian", "Cooking class", "Market shopping"],
    rate: 160,
    rateUnit: "per dinner (up to 6)",
    includes: ["Market shopping", "3-course menu", "Table service", "Full clean-up"],
    packages: [
      { name: "Family dinner", detail: "3 courses for up to 6", price: 160 },
      { name: "Feast for 12", detail: "Mezze, two mains, dessert", price: 320 },
      { name: "Cook with the chef", detail: "Souk run plus lesson", price: 210 },
    ],
    availability: "Every evening except Friday lunch",
    cancellation: "Free up to 24h before",
  },
  {
    id: "pro-chef-2",
    professionId: "chef",
    city: "Cape Town",
    name: "Thandi Mokoena",
    headline: "Private chef — braai, seafood & plant-based",
    image: "/images/pro-chef-2.jpg",
    bio: "Ex-restaurant sous chef doing villa dinners across Camps Bay and Constantia. Big on line-caught fish, Cape Malay spice and a proper braai when the wind behaves.",
    rating: 4.9,
    jobs: 220,
    years: 11,
    languages: ["English", "Xhosa", "Afrikaans"],
    skills: ["Seafood", "Braai", "Plant-based", "Wine pairing"],
    rate: 190,
    rateUnit: "per dinner (up to 8)",
    includes: ["Menu design", "Groceries", "Wine pairing notes", "Kitchen left spotless"],
    packages: [
      { name: "Sunset braai", detail: "Grill spread for 8", price: 190 },
      { name: "Tasting menu", detail: "5 courses, plated", price: 380 },
      { name: "Week of meals", detail: "5 dinners prepped and stored", price: 720 },
    ],
    availability: "Tuesday to Sunday",
    cancellation: "Free up to 48h before",
  },
  {
    id: "pro-barber-1",
    professionId: "barber",
    city: "Tokyo",
    name: "Sho Nakamura",
    headline: "Hotel-visit barber — fades & hot-towel shaves",
    image: "/images/pro-barber-1.jpg",
    bio: "Runs a two-chair shop in Nakameguro and travels to hotels with a full kit. Precise skin fades, straight-razor shaves and beard shaping without the language barrier.",
    rating: 4.9,
    jobs: 980,
    years: 13,
    languages: ["Japanese", "English"],
    skills: ["Skin fade", "Scissor cut", "Hot-towel shave", "Beard shaping"],
    rate: 70,
    rateUnit: "per cut",
    includes: ["Travel to your hotel", "Full kit and towels", "Styling advice", "Clean-up"],
    packages: [
      { name: "Cut", detail: "Consultation plus finish", price: 70 },
      { name: "Cut and shave", detail: "Hot towel, straight razor", price: 110 },
      { name: "Group of three", detail: "Same room, back to back", price: 180 },
    ],
    availability: "Daily 10:00-20:00",
    cancellation: "Free up to 6h before",
  },
  {
    id: "pro-barber-2",
    professionId: "barber",
    city: "Cape Town",
    name: "Naledi Dube",
    headline: "Mobile stylist — braids, locs & blowouts",
    image: "/images/pro-barber-2.jpg",
    bio: "Fifteen years of protective styling. Comes to your stay with chairs, steamer and product, and will do the whole family in one sitting before a shoot or a wedding.",
    rating: 4.8,
    jobs: 610,
    years: 15,
    languages: ["English", "Zulu"],
    skills: ["Braids", "Locs", "Silk press", "Kids' hair"],
    rate: 95,
    rateUnit: "per session",
    includes: ["Travel to your stay", "Products included", "Wash and treatment", "Aftercare notes"],
    packages: [
      { name: "Blowout", detail: "Wash, treat, style", price: 95 },
      { name: "Braids", detail: "Knotless, 3-5 hours", price: 180 },
      { name: "Family session", detail: "Up to 4 people", price: 300 },
    ],
    availability: "Mon-Sat, 07:00 start possible",
    cancellation: "Free up to 24h before",
  },
  {
    id: "pro-shopper-1",
    professionId: "shopper",
    city: "Marrakech",
    name: "Yasmine El Fassi",
    headline: "Personal shopper — souks, rugs & tailoring",
    image: "/images/pro-shopper-1.jpg",
    bio: "Buys for interior designers and knows which medina workshops are the real makers. Negotiates in darija, arranges shipping, and keeps you out of the commission traps.",
    rating: 5,
    jobs: 280,
    years: 10,
    languages: ["Arabic", "French", "English"],
    skills: ["Rugs", "Ceramics", "Tailoring", "Negotiation", "Shipping"],
    rate: 130,
    rateUnit: "per half day",
    includes: ["Pre-trip wishlist call", "Negotiation", "Porter for bags", "Shipping arranged"],
    packages: [
      { name: "Souk half day", detail: "4 hours, curated route", price: 130 },
      { name: "Full day buy", detail: "8 hours, workshops included", price: 240 },
      { name: "Buy for me", detail: "Sourced and shipped, no trip needed", price: 180 },
    ],
    availability: "Daily except Friday morning",
    cancellation: "Free up to 24h before",
  },
  {
    id: "pro-shopper-2",
    professionId: "shopper",
    city: "Tokyo",
    name: "Aya Kobayashi",
    headline: "Personal shopper — vintage, denim & sneakers",
    image: "/images/pro-shopper-2.jpg",
    bio: "Styles clients through Shimokitazawa, Harajuku and the Ginza department stores. Handles tax-free paperwork and sizing conversions so nothing arrives home unwearable.",
    rating: 4.9,
    jobs: 350,
    years: 8,
    languages: ["Japanese", "English"],
    skills: ["Vintage", "Streetwear", "Denim", "Tax-free help"],
    rate: 150,
    rateUnit: "per half day",
    includes: ["Style consult", "Store route", "Tax-free paperwork", "Sizing conversion"],
    packages: [
      { name: "Vintage crawl", detail: "4 hours, Shimokitazawa", price: 150 },
      { name: "Full wardrobe day", detail: "8 hours across districts", price: 280 },
      { name: "Sneaker hunt", detail: "3 hours, release-day strategy", price: 130 },
    ],
    availability: "Weekdays, some Saturdays",
    cancellation: "Free up to 48h before",
  },
  {
    id: "pro-interpreter-1",
    professionId: "interpreter",
    city: "Tokyo",
    name: "Hiroko Tanabe",
    headline: "Business interpreter — JP/EN, certified",
    image: "/images/pro-interpreter-1.jpg",
    bio: "Certified conference interpreter with twenty years in manufacturing and finance meetings. Also does hospital visits and contract reading when a trip goes sideways.",
    rating: 5,
    jobs: 500,
    years: 20,
    languages: ["Japanese", "English", "Korean"],
    skills: ["Consecutive", "Business", "Medical", "Document reading"],
    rate: 320,
    rateUnit: "per half day",
    includes: ["Prep call", "Glossary of your terms", "Note-taking", "Written summary"],
    packages: [
      { name: "Meeting support", detail: "4 hours on site", price: 320 },
      { name: "Full day", detail: "8 hours plus summary", price: 580 },
      { name: "Phone standby", detail: "On call for a day", price: 190 },
    ],
    availability: "Weekdays, book 3 days ahead",
    cancellation: "Free up to 72h before",
  },
  {
    id: "pro-interpreter-2",
    professionId: "interpreter",
    city: "Rio de Janeiro",
    name: "Rafael Duarte",
    headline: "Interpreter & fixer — PT/EN/ES",
    image: "/images/pro-interpreter-2.jpg",
    bio: "Worked with news crews for a decade, so he translates and unblocks things at the same time — permits, hospital desks, police reports, awkward negotiations.",
    rating: 4.8,
    jobs: 240,
    years: 12,
    languages: ["Portuguese", "English", "Spanish"],
    skills: ["Live translation", "Fixing", "Permits", "Emergency support"],
    rate: 210,
    rateUnit: "per half day",
    includes: ["On-site translation", "Local phone number", "Transport coordination", "Written notes"],
    packages: [
      { name: "Half day", detail: "4 hours with you", price: 210 },
      { name: "Full day fixer", detail: "8 hours, problems solved", price: 380 },
      { name: "Airport to hotel", detail: "Arrival support only", price: 120 },
    ],
    availability: "Any day, short notice possible",
    cancellation: "Free up to 24h before",
  },
  {
    id: "pro-security-1",
    professionId: "security",
    city: "Rio de Janeiro",
    name: "Bruno Ferreira",
    headline: "Licensed close protection officer",
    image: "/images/pro-security-1.jpg",
    bio: "Fifteen years in executive protection, ex-military, fully licensed and insured. Low-profile, plain clothes, plans routes and venues before you ever step out.",
    rating: 4.9,
    jobs: 300,
    years: 15,
    languages: ["Portuguese", "English"],
    skills: ["Close protection", "Route planning", "Secure driving", "Risk assessment"],
    rate: 420,
    rateUnit: "per day",
    includes: ["Advance route recce", "Licensed and insured", "Discreet dress", "24h contact line"],
    packages: [
      { name: "Evening cover", detail: "6 hours, one officer", price: 260 },
      { name: "Full day", detail: "12 hours, one officer", price: 420 },
      { name: "Two-officer detail", detail: "12 hours plus vehicle", price: 890 },
    ],
    availability: "Any day, 24h notice",
    cancellation: "Free up to 72h before",
  },
  {
    id: "pro-security-2",
    professionId: "security",
    city: "Cape Town",
    name: "Sipho Ndlovu",
    headline: "Security driver & personal escort",
    image: "/images/pro-security-2.jpg",
    bio: "Armed-response background, now drives visiting families and film crews. Knows which roads to skip after dark and keeps the day calm and on schedule.",
    rating: 4.8,
    jobs: 410,
    years: 13,
    languages: ["English", "Xhosa", "Afrikaans"],
    skills: ["Secure driving", "Escort", "Airport transfers", "Family details"],
    rate: 360,
    rateUnit: "per day incl. vehicle",
    includes: ["Vehicle and fuel", "Licensed officer", "Airport transfers", "Live check-ins"],
    packages: [
      { name: "Airport detail", detail: "Meet, escort, deliver", price: 140 },
      { name: "Full day", detail: "10 hours with vehicle", price: 360 },
      { name: "Week retainer", detail: "6 days, same officer", price: 1900 },
    ],
    availability: "Daily, including public holidays",
    cancellation: "Free up to 48h before",
  },
  {
    id: "pro-babysitter-1",
    professionId: "babysitter",
    city: "Santorini",
    name: "Sofia Papadaki",
    headline: "Vetted nanny — infants to school age",
    image: "/images/pro-babysitter-1.jpg",
    bio: "Qualified early-years teacher, paediatric first aid current, background checked. Brings a bag of games and will do bedtime routines exactly the way you already do them.",
    rating: 5,
    jobs: 460,
    years: 9,
    languages: ["Greek", "English"],
    skills: ["Infants", "Toddlers", "First aid", "Bedtime routines"],
    rate: 22,
    rateUnit: "per hour",
    includes: ["Background check", "Paediatric first aid", "Activity kit", "Photo updates"],
    packages: [
      { name: "Evening sit", detail: "4 hours, up to 2 kids", price: 88 },
      { name: "Beach day", detail: "8 hours with the kids", price: 170 },
      { name: "Week of evenings", detail: "5 nights, 4 hours each", price: 400 },
    ],
    availability: "Evenings and full days, 24h notice",
    cancellation: "Free up to 12h before",
  },
  {
    id: "pro-babysitter-2",
    professionId: "babysitter",
    city: "Bali",
    name: "Kadek Sari",
    headline: "Villa nanny & kids' activity host",
    image: "/images/pro-babysitter-2.jpg",
    bio: "Eight years with villa families in Canggu and Ubud. Swim-safe, makes the afternoon into craft time or a rice-field walk, and cooks simple kid meals if needed.",
    rating: 4.9,
    jobs: 380,
    years: 8,
    languages: ["Indonesian", "English"],
    skills: ["Pool safety", "Crafts", "Kids' meals", "Toddlers"],
    rate: 14,
    rateUnit: "per hour",
    includes: ["Water-safety trained", "Craft materials", "Light meals", "Daily notes"],
    packages: [
      { name: "Half day", detail: "5 hours at your villa", price: 70 },
      { name: "Full day", detail: "10 hours including meals", price: 130 },
      { name: "Night cover", detail: "Overnight with infant", price: 160 },
    ],
    availability: "Daily, live-in possible",
    cancellation: "Free up to 24h before",
  },
  {
    id: "pro-event-planner-1",
    professionId: "event-planner",
    city: "Santorini",
    name: "Dimitra Kalogeri",
    headline: "Proposal & micro-wedding planner",
    image: "/images/pro-event-planner-1.jpg",
    bio: "Plans caldera proposals and 20-guest weddings end to end — permits, florals, musicians, the boat. Has a plan B venue for every wind forecast.",
    rating: 5,
    jobs: 210,
    years: 12,
    languages: ["Greek", "English", "Italian"],
    skills: ["Proposals", "Micro-weddings", "Permits", "Florals", "Vendor management"],
    rate: 850,
    rateUnit: "per event",
    includes: ["Venue and permits", "Vendor booking", "On-the-day coordination", "Weather plan B"],
    packages: [
      { name: "Proposal setup", detail: "Private terrace, florals, photographer", price: 850 },
      { name: "Micro-wedding", detail: "Up to 20 guests, full planning", price: 4200 },
      { name: "Birthday dinner", detail: "Venue, menu, music for 12", price: 1300 },
    ],
    availability: "April to October, book 3 weeks ahead",
    cancellation: "Deposit refundable up to 14 days",
  },
  {
    id: "pro-event-planner-2",
    professionId: "event-planner",
    city: "Marrakech",
    name: "Omar Chraibi",
    headline: "Riad party & desert event producer",
    image: "/images/pro-event-planner-2.jpg",
    bio: "Produces rooftop dinners, riad birthdays and desert-camp nights with gnawa musicians. Handles the logistics that make a Marrakech party actually run on time.",
    rating: 4.8,
    jobs: 170,
    years: 11,
    languages: ["Arabic", "French", "English"],
    skills: ["Riad events", "Desert camps", "Live music", "Catering", "Décor"],
    rate: 700,
    rateUnit: "per event",
    includes: ["Venue sourcing", "Décor and lighting", "Musicians", "Transport for guests"],
    packages: [
      { name: "Rooftop dinner", detail: "Up to 15 guests, catered", price: 700 },
      { name: "Riad celebration", detail: "40 guests, décor and DJ", price: 2400 },
      { name: "Desert night", detail: "Camp, dinner, gnawa band", price: 3100 },
    ],
    availability: "Year round, book 2 weeks ahead",
    cancellation: "50% deposit non-refundable",
  },
  {
    id: "pro-freelancer-1",
    professionId: "freelancer",
    city: "Bali",
    name: "Wayan Surya",
    headline: "Trip fixer, driver & general assistant",
    image: "/images/pro-freelancer-1.jpg",
    bio: "The person you call when something needs doing — SIM cards, scooter rentals, temple permits, a last-minute doctor. Drives too, so the day never stalls.",
    rating: 4.9,
    jobs: 540,
    years: 10,
    languages: ["Indonesian", "English"],
    skills: ["Driving", "Errands", "Permits", "Bookings", "Problem solving"],
    rate: 90,
    rateUnit: "per day",
    includes: ["Car and fuel", "Local SIM setup", "Bookings on your behalf", "WhatsApp on call"],
    packages: [
      { name: "Half day", detail: "5 hours with car", price: 55 },
      { name: "Full day", detail: "10 hours with car", price: 90 },
      { name: "Week retainer", detail: "6 days, same fixer", price: 480 },
    ],
    availability: "Daily, same-day possible",
    cancellation: "Free up to 12h before",
  },
  {
    id: "pro-freelancer-2",
    professionId: "freelancer",
    city: "Cape Town",
    name: "Lerato Khumalo",
    headline: "Remote-work assistant & city fixer",
    image: "/images/pro-freelancer-2.jpg",
    bio: "Sets up long-stay visitors: co-working desks, sim and banking, gym passes, reliable trades for the apartment. Ex-hotel concierge, so nothing surprises her.",
    rating: 4.8,
    jobs: 260,
    years: 7,
    languages: ["English", "Sotho"],
    skills: ["Concierge", "Admin", "Long-stay setup", "Restaurant access"],
    rate: 110,
    rateUnit: "per day",
    includes: ["Setup checklist", "Local sim and banking help", "Reservations", "Trusted trades list"],
    packages: [
      { name: "Arrival setup", detail: "One day, everything sorted", price: 110 },
      { name: "Weekly support", detail: "3 days a week", price: 290 },
      { name: "Reservations only", detail: "Bookings for your stay", price: 60 },
    ],
    availability: "Weekdays, weekends on request",
    cancellation: "Free up to 24h before",
  },
];

export function prosFor(professionId: string, city: string, query: string): TravelPro[] {
  const q = query.trim().toLowerCase();
  return PROS.filter((p) => {
    if (professionId !== "all" && p.professionId !== professionId) return false;
    if (city !== "all" && p.city !== city) return false;
    if (!q) return true;
    return (
      p.name.toLowerCase().includes(q) ||
      p.headline.toLowerCase().includes(q) ||
      p.city.toLowerCase().includes(q) ||
      p.skills.some((s) => s.toLowerCase().includes(q))
    );
  });
}

export function countFor(professionId: ProfessionId): number {
  return PROS.filter((p) => p.professionId === professionId).length;
}
