/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PassportVisaRouteImport } from './routes/passport-visa'
import { Route as HireRouteImport } from './routes/hire'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents/index'
import { Route as AuthenticatedTripsNewRouteImport } from './routes/_authenticated/trips/new'
import { Route as AuthenticatedTripsTripIdRouteImport } from './routes/_authenticated/trips/$tripId'
import { Route as AuthenticatedDocumentsApplyRouteImport } from './routes/_authenticated/documents/apply'
import { Route as AuthenticatedDocumentsReferenceRouteImport } from './routes/_authenticated/documents/$reference'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin/documents'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportVisaRoute = PassportVisaRouteImport.update({
  id: '/passport-visa',
  path: '/passport-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const HireRoute = HireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTripsNewRoute = AuthenticatedTripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTripsTripIdRoute =
  AuthenticatedTripsTripIdRouteImport.update({
    id: '/trips/$tripId',
    path: '/trips/$tripId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsApplyRoute =
  AuthenticatedDocumentsApplyRouteImport.update({
    id: '/documents/apply',
    path: '/documents/apply',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsReferenceRoute =
  AuthenticatedDocumentsReferenceRouteImport.update({
    id: '/documents/$reference',
    path: '/documents/$reference',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/admin/documents',
    path: '/admin/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/hire': typeof HireRoute
  '/passport-visa': typeof PassportVisaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/track': typeof TrackRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/documents/$reference': typeof AuthenticatedDocumentsReferenceRoute
  '/documents/apply': typeof AuthenticatedDocumentsApplyRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/trips/new': typeof AuthenticatedTripsNewRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/hire': typeof HireRoute
  '/passport-visa': typeof PassportVisaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/track': typeof TrackRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/documents/$reference': typeof AuthenticatedDocumentsReferenceRoute
  '/documents/apply': typeof AuthenticatedDocumentsApplyRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/trips/new': typeof AuthenticatedTripsNewRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/hire': typeof HireRoute
  '/passport-visa': typeof PassportVisaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/track': typeof TrackRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/documents/$reference': typeof AuthenticatedDocumentsReferenceRoute
  '/_authenticated/documents/apply': typeof AuthenticatedDocumentsApplyRoute
  '/_authenticated/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/_authenticated/trips/new': typeof AuthenticatedTripsNewRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/hire'
    | '/passport-visa'
    | '/reset-password'
    | '/track'
    | '/dashboard'
    | '/admin/documents'
    | '/documents/$reference'
    | '/documents/apply'
    | '/trips/$tripId'
    | '/trips/new'
    | '/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/hire'
    | '/passport-visa'
    | '/reset-password'
    | '/track'
    | '/dashboard'
    | '/admin/documents'
    | '/documents/$reference'
    | '/documents/apply'
    | '/trips/$tripId'
    | '/trips/new'
    | '/documents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/explore'
    | '/hire'
    | '/passport-visa'
    | '/reset-password'
    | '/track'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/documents'
    | '/_authenticated/documents/$reference'
    | '/_authenticated/documents/apply'
    | '/_authenticated/trips/$tripId'
    | '/_authenticated/trips/new'
    | '/_authenticated/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  HireRoute: typeof HireRoute
  PassportVisaRoute: typeof PassportVisaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport-visa': {
      id: '/passport-visa'
      path: '/passport-visa'
      fullPath: '/passport-visa'
      preLoaderRoute: typeof PassportVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips/new': {
      id: '/_authenticated/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AuthenticatedTripsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips/$tripId': {
      id: '/_authenticated/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AuthenticatedTripsTripIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/apply': {
      id: '/_authenticated/documents/apply'
      path: '/documents/apply'
      fullPath: '/documents/apply'
      preLoaderRoute: typeof AuthenticatedDocumentsApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$reference': {
      id: '/_authenticated/documents/$reference'
      path: '/documents/$reference'
      fullPath: '/documents/$reference'
      preLoaderRoute: typeof AuthenticatedDocumentsReferenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedDocumentsReferenceRoute: typeof AuthenticatedDocumentsReferenceRoute
  AuthenticatedDocumentsApplyRoute: typeof AuthenticatedDocumentsApplyRoute
  AuthenticatedTripsTripIdRoute: typeof AuthenticatedTripsTripIdRoute
  AuthenticatedTripsNewRoute: typeof AuthenticatedTripsNewRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedDocumentsReferenceRoute: AuthenticatedDocumentsReferenceRoute,
  AuthenticatedDocumentsApplyRoute: AuthenticatedDocumentsApplyRoute,
  AuthenticatedTripsTripIdRoute: AuthenticatedTripsTripIdRoute,
  AuthenticatedTripsNewRoute: AuthenticatedTripsNewRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  HireRoute: HireRoute,
  PassportVisaRoute: PassportVisaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
